{{- if .Values.alert.k8sPod.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "k8s-prometheus-rules.labels" . | nindent 4 }}
  name: {{ include "k8s-prometheus-rules.fullname" . }}-alert-k8s-pod
  namespace: {{ .Values.namespace }}
spec:
  groups:
  - name: k8s-pod
    rules:
      {{- if .Values.alert.k8sPod.kubernetesContainerOomKiller }}
      - alert: KubernetesContainerOomKiller
        expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 5m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
        for: 0m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: warning
          target: "Pod/Container : {{ "{{" }} $labels.pod {{ "}}" }}/{{ "{{" }} $labels.container {{ "}}" }}"
          current: ' → OOMKilled {{ "{{" }} printf "%.0f" $value {{ "}}" }} 번 발생'
        annotations:
          summary: "Kubernetes container oom killer"
          description: "컨테이너에 지난 5분 동안 OOMKilled가 1번 이상 발생했습니다."
          # description: "Container has been OOMKilled in the last 5 minutes."
      {{- end }}
      {{- if .Values.alert.k8sPod.kubernetesPodNotHealthy }}
      - alert: KubernetesPodNotHealthy
        expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
        for: 5m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: critical
          target: "Pod : {{ "{{" }} $labels.pod {{ "}}" }}"
          current: " → Pending|Unknown|Failed 상태"
        annotations:
          summary: "Kubernetes Pod not healthy"
          description: "파드 비정상 상태가 5분 이상 지속되고 있습니다."
          # description: "Pod has been in a non-ready state for longer than 5 minutes."
      {{- end }}
      {{- if .Values.alert.k8sPod.kubernetesPodCrashLooping }}
      - alert: KubernetesPodCrashLooping
        expr: increase(kube_pod_container_status_restarts_total[1m]) > 3
        for: 2m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: warning
          target: "Pod : {{ "{{" }} $labels.pod {{ "}}" }}"
          current: " → Crash Loop 상태"
        annotations:
          summary: "Kubernetes pod crash looping"
          description: "파드가 Crash Loop 상태입니다."
          # description: "Pod is crash looping"
      {{- end }}
{{- end }}