{{- if .Values.alert.k8sWorkload.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "k8s-prometheus-rules.labels" . | nindent 4 }}
  name: {{ include "k8s-prometheus-rules.fullname" . }}-alert-k8s-workload
  namespace: {{ .Values.namespace }}
spec:
  groups:
  - name: k8s-workload
    rules:
      {{- if .Values.alert.k8sWorkload.kubernetesJobFailed }}
      - alert: KubernetesJobFailed
        expr: kube_job_status_failed > 0
        for: 0m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: warning
          target: "Job : {{ "{{" }} $labels.job_name {{ "}}" }}"
          current: " → 완료 실패"
        annotations:
          summary: "Kubernetes Job failed"
          description: "Job을 완료하지 못했습니다."
          # description: "Job failed to complete"
      {{- end }}
      {{- if .Values.alert.k8sWorkload.kubernetesCronjobSuspended }}
      - alert: KubernetesCronjobSuspended
        expr: kube_cronjob_spec_suspend != 0
        for: 0m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: warning
          target: "Cronjob : {{ "{{" }} $labels.cronjob {{ "}}" }}"
          current: " → 중지 상태"
        annotations:
          summary: "Kubernetes CronJob suspended"
          description: "CronJob이 중지 상태입니다."
          # description: "CronJob is suspended"
      {{- end }}
      {{- if .Values.alert.k8sWorkload.kubernetesStatefulsetDown }}
      - alert: KubernetesStatefulsetDown
        expr: kube_statefulset_replicas - kube_statefulset_status_replicas_ready > 0
        for: 1m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: critical
          target: "Statefulset : {{ "{{" }} $labels.statefulset {{ "}}" }}"
          current: ' → {{ "{{" }} printf "%.0f" $value {{ "}}" }} 개의 파드 Not Ready 상태'
        annotations:
          summary: "Kubernetes StatefulSet down"
          description: "StatefulSet에 속한 파드의 Not Ready 상태가 1분 이상 지속되고 있습니다."
          # description: "A StatefulSet went down"
      {{- end }}
      {{- if .Values.alert.k8sWorkload.kubernetesHpaScalingAbility }}
      - alert: KubernetesHpaScalingAbility
        expr: kube_horizontalpodautoscaler_status_condition{status="false", condition="AbleToScale"} == 1
        for: 2m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: warning
          target: "HPA : {{ "{{" }} $labels.horizontalpodautoscaler {{ "}}" }}"
          current: " → Scaling을 할 수 없는 상태"
        annotations:
          summary: "Kubernetes HPA scaling ability"
          description: "HPA가 파드 Scale in/out을 할 수 없는 상태입니다."
          # description: "Pod is unable to scale"
      {{- end }}
      {{- if .Values.alert.k8sWorkload.kubernetesHpaMetricAvailability }}
      - alert: KubernetesHpaMetricAvailability
        expr: kube_horizontalpodautoscaler_status_condition{status="false", condition="ScalingActive"} == 1
        for: 0m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: warning
          target: "HPA : {{ "{{" }} $labels.horizontalpodautoscaler {{ "}}" }}"
          current: " → Scaling을 위한 메트릭 수집 불가 상태"
        annotations:
          summary: "Kubernetes HPA metric availability"
          description: "HPA를 위한 메트릭을 수집할 수 없는 상태입니다. 메트릭을 위한 apiservice를 확인하세요.(ex.metrics-server)"
          # description: "HPA is not able to collect metrics"
      {{- end }}
      {{- if .Values.alert.k8sWorkload.kubernetesHpaScaleCapability }}
      - alert: KubernetesHpaScaleCapability
        expr: kube_horizontalpodautoscaler_status_desired_replicas >= kube_horizontalpodautoscaler_spec_max_replicas
        for: 2m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: info
          target: "HPA : {{ "{{" }} $labels.horizontalpodautoscaler {{ "}}" }}"
          current: " → Max replica 도달"
        annotations:
          summary: "Kubernetes HPA scale capability"
          description: "HPA에 설정한 최대 파드 개수만큼 Scaling out 됐습니다."
          # description: "The maximum number of desired Pods has been hit"
      {{- end }}
      {{- if .Values.alert.k8sWorkload.kubernetesReplicassetMismatch }}
      - alert: KubernetesReplicassetMismatch
        expr: kube_replicaset_spec_replicas - kube_replicaset_status_ready_replicas > 0
        for: 10m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: warning
          target: "Replicaset : {{ "{{" }} $labels.replicaset {{ "}}" }}"
          current: ' → {{ "{{" }} printf "%.0f" $value {{ "}}" }} 개의 파드 Not Ready 상태'
        annotations:
          summary: "Kubernetes ReplicasSet mismatch"
          description: "ReplicaSet에 속한 파드의 Not Ready 상태가 10분 이상 지속되고 있습니다."
          # description: "Deployment Replicas mismatch"
      {{- end }}
      {{- if .Values.alert.k8sWorkload.kubernetesDeploymentReplicasMismatch }}
      - alert: KubernetesDeploymentReplicasMismatch
        expr: kube_deployment_spec_replicas - kube_deployment_status_replicas_available > 0
        for: 10m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: warning
          target: "Deployment : {{ "{{" }} $labels.deployment {{ "}}" }}"
          current: ' → {{ "{{" }} printf "%.0f" $value {{ "}}" }} 개의 파드 Not Ready 상태'
        annotations:
          summary: "Kubernetes Deployment replicas mismatch"
          description: "Deployment에 속한 파드의 Not Ready 상태가 10분 이상 지속되고 있습니다."
          # description: "Deployment Replicas mismatch"
      {{- end }}
      {{- if .Values.alert.k8sWorkload.kubernetesStatefulsetReplicasMismatch }}
      - alert: KubernetesStatefulsetReplicasMismatch
        expr: kube_statefulset_status_replicas - kube_statefulset_status_replicas_ready > 0
        for: 10m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: warning
          target: "Statefulset : {{ "{{" }} $labels.statefulset {{ "}}" }}"
          current: ' → {{ "{{" }} printf "%.0f" $value {{ "}}" }} 개의 파드 Not Ready 상태'
        annotations:
          summary: "Kubernetes StatefulSet replicas mismatch"
          description: "StatefulSet에 속한 파드의 Not Ready 상태가 10분 이상 지속되고 있습니다."
          # description: "A StatefulSet does not match the expected number of replicas."
      {{- end }}
      {{- if .Values.alert.k8sWorkload.kubernetesDeploymentGenerationMismatch }}
      - alert: KubernetesDeploymentGenerationMismatch
        expr: kube_deployment_status_observed_generation != kube_deployment_metadata_generation
        for: 10m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: critical
          target: "Deployment : {{ "{{" }} $labels.deployment {{ "}}" }}"
          current: " → 업데이트 문제 발생"
        annotations:
          summary: "Kubernetes Deployment generation mismatch"
          description: "Deployment 업데이트에 문제가 발생했습니다. Rollback이 필요할 수 있습니다."
          # description: "A Deployment has failed but has not been rolled back."
      {{- end }}
      {{- if .Values.alert.k8sWorkload.kubernetesStatefulsetGenerationMismatch }}
      - alert: KubernetesStatefulsetGenerationMismatch
        expr: kube_statefulset_status_observed_generation != kube_statefulset_metadata_generation
        for: 10m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: critical
          target: "Statefulset : {{ "{{" }} $labels.statefulset {{ "}}" }}"
          current: " → 업데이트 문제 발생"
        annotations:
          summary: "Kubernetes StatefulSet generation mismatch"
          description: "StatefulSet 업데이트에 문제가 발생했습니다. Rollback이 필요할 수 있습니다."
          # description: "A StatefulSet has failed but has not been rolled back."
      {{- end }}
      {{- if .Values.alert.k8sWorkload.kubernetesStatefulsetUpdateNotRolledOut }}
      - alert: KubernetesStatefulsetUpdateNotRolledOut
        expr: max without (revision) (kube_statefulset_status_current_revision unless kube_statefulset_status_update_revision) * (kube_statefulset_replicas != kube_statefulset_status_replicas_updated)
        for: 10m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: warning
          target: "Statefulset : {{ "{{" }} $labels.statefulset {{ "}}" }}"
          current: " → 업데이트 지연"
        annotations:
          summary: "Kubernetes StatefulSet update not rolled out"
          description: "StatefulSet 업데이트가 10분 이상 진행 중입니다."
          # description: "StatefulSet update has not been rolled out."
      {{- end }}
      {{- if .Values.alert.k8sWorkload.kubernetesDaemonsetRolloutStuck }}
      - alert: KubernetesDaemonsetRolloutStuck
        expr: kube_daemonset_status_number_ready / kube_daemonset_status_desired_number_scheduled * 100 < 100 or kube_daemonset_status_desired_number_scheduled - kube_daemonset_status_current_number_scheduled > 0
        for: 10m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: warning
          target: "Daemonset : {{ "{{" }} $labels.daemonset {{ "}}" }}"
          current: " → 파드 Not Scheduled or Not Ready 상태"
        annotations:
          summary: "Kubernetes DaemonSet rollout stuck"
          description: "DaemonSet에 10분 이상 Scheduling 되지 않았거나 Not Ready 상태인 파드가 존재합니다."
          # description: "Some Pods of DaemonSet are not scheduled or not ready"
      {{- end }}
      {{- if .Values.alert.k8sWorkload.kubernetesDaemonsetMisscheduled }}
      - alert: KubernetesDaemonsetMisscheduled
        expr: kube_daemonset_status_number_misscheduled > 0
        for: 1m
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: critical
          target: "Daemonset : {{ "{{" }} $labels.daemonset {{ "}}" }}"
          current: " → 파드 Scheduling 실패"
        annotations:
          summary: "Kubernetes DaemonSet misscheduled"
          description: "DaemonSet에 Scheduling을 실패한 파드가 존재합니다."
          # description: "Some DaemonSet Pods are running where they are not supposed to run"
      {{- end }}
      {{- if .Values.alert.k8sWorkload.kubernetesJobSlowCompletion }}
      - alert: KubernetesJobSlowCompletion
        expr: kube_job_spec_completions - kube_job_status_succeeded > 0
        for: 24h
        labels:
          tenant: {{ .Values.tenant }}
          owned: mimir
          severity: critical
          target: "Job : {{ "{{" }} $labels.job_name {{ "}}" }}"
          current: " → 완료되지 않음"
        annotations:
          summary: "Kubernetes job slow completion"
          description: "Job이 24시간 넘도록 완료되지 않았습니다."
          # description: "Kubernetes Job did not complete in time."
      {{- end }}
{{- end }}