{{- if .Values.record.podMetric.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "k8s-prometheus-rules.labels" . | nindent 4 }}
  name: {{ include "k8s-prometheus-rules.fullname" . }}-record-pod-metric
  namespace: {{ .Values.namespace }}
spec:
  groups:
  - name: pod-metric
    rules:
      - expr:
          sum(node_namespace_pod_container:container_memory_working_set_bytes)by(namespace, node, pod, container)
          /
          sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests)by(namespace, node, pod, container)
        record: namespace_node_pod_container:memory_ratio:request
      - expr:
          sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate)by(namespace, node, pod, container)
          /
          sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests)by(namespace, node, pod, container)
        record: namespace_node_pod_container:cpu_ratio:request
{{- end }}